### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/soniprev#1]
- [x] Language menu should be opened on click and has wrong languages
- [x] If possible add transparency on dropdown menu and language menu
- [x] When the menu has solid background it should have some transparency and check the blue color if it's correct, please.
- [x] On tablet size the menu cuts a bit the last characters on the right.

**Comment by ShkredovDmitriy** [comment]
4. On tablet size the menu cuts a bit the last characters on the right. Give a screenshot please.

**Comment by lpissinali** [comment]
http://prntscr.com/r51i2z

**Comment by ShkredovDmitriy** [comment]
fixed
