### ISSUE TITLE
Improve the map

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/soniprev#9]
I didn't know that the map had some animation on it, we need to code it as close as possible from the mockups. I can try give it a hand if there are issues.

**Comment by donrus** [comment]
I wrote you, we couldn't export this map in svg format. Please notice, how to do that, and we do this animation.

**Comment by lpissinali** [comment]
My idea would be to have just the map without the points as a background image, then absolute position the markers and when selected just use some transformation to increase it's size. You don't need to highlight the map area.
